# НЕ РЕДАКТИРУЙТЕ ЭТОТ ФАЙЛ!
# Правила для пропуска строк
(/duckdns/) {next}
(/linode\.com/) {next}
(/upcloud\.com/) {next}
(/\.sl\.pt/) {next}
(/\.biz\.ski/) {next}
(/\.sloat\.biz/) {next}
(/\.new-rutor\.org/) {next}
(/\.traderc\.biz/) {next}
(/\.o-q\.biz/) {next}
(/\.dcge\.biz/) {next}
(/fonbet/) {next}
(/betcity/) {next}
(/zerkalo/ && !/zerkalo\.io/) {next}
(/zigzag/) {next}
(/zenitbet/) {next}
(/winline/) {next}
(/ttrcasino/) {next}
(/paripartners/) {next}
(/parimatch/) {next}
(/ligastavok/) {next}
(/liga-stavok/) {next}
(/baltplay/) {next}
(/azino777/) {next}
(/azino.*777/) {next}
(/777.*azino/) {next}
(/vulkan/) {next}
(/leonbet/) {next}
(/ru\.leon/) {next}
(/ru\.adleon/) {next}
(/leonaccess/) {next}
(/leon-[0-9]{3}/) {next}
(/pm-[0-9]{2,3}\./) {next}
(/mf-[0-9]{2,3}\.online/) {next}
(/fon-[0-9]{2,3}\./) {next}
(/most.{3}\./) {next}
(/casino\-/) {next}
(/bcity\-/) {next}
(/1x\-/) {next}
(/^1xbet[^.]/) {next}
(/^1xbet-/) {next}
(/1xmob/) {next}
#(/melbet/) {next}
(/bk\-info/) {next}
(/bkinfo/) {next}
(/marathon/) {next}
(/gaminator/) {next}
(/joycasino/) {next}
(/goldenstar/) {next}
/marafon/ {next}
/olimp-tv\.org/ {print}
/olimp/ {next}
/kasino/ {next}
/depozit/ {next}
/kazino/ {next}
#/777/ {next}
/casino/ {next}
/admiral/ {next}
/zerkala/ {next}
/avtomat/ {next}
/igrat/ {next}
/azart/ {next}
#/besplatno/ {next}
/sloty/ {next}
/bet-boom/ {next}
/betsbc/ {next}
/^bk-/ {next}
/^bkr/ {next}
/bkinf0/ {next}
/bukmeker/ {next}
/ruletka/ {next}
/vulcan/ {next}
/vylkan/ {next}
/wulcan/ {next}
/wulkan/ {next}
/vullkan/ {next}
/volcan/ {next}
/^vlc/ {next}
/^vlk/ {next}
/eldorado/ {next}
/lotto/ {next}
/lottery/ {next}
/fbmetrix/ {next}
/^diplom-/ {next}
/^dosug-/ {next}
/^dosug[0-9]{2}/ {next}
/fon-bet/ {next}
/^hydra[0-9]{2}/ {next}
/^intim[0-9]{2}/ {next}
/^livetv[0-9]{2}/ {next}
/marafon/ {next}
#/^melb/ {next}
/^melm/ {next}
/^mf-[0-9]{2}/ {next}
/^most/ {next}
#/^new-/ {next}
/^pari-/ {next}
/^pokerdom/ {next}
/prostitutki/ {next}
/spravka/ {next}
/mossst/ {next}
/mostbet/ {next}
/diplom/ {next}
/pharaon/ {next}
/fortuna/ {next}
/^rotate/ {next}
/^ref.{5}\./ {next}
/play\-/ {next}
/^1w.{3,4}\./ {next}
/^mylove[0-9]{2,3}\./ {next}
#/^1x.{3,4}\./ {next}
/^mirror[0-9]{2,3}\./ {next}
/^mob.{3,4}\./ {next}
#/^777/ {next}
/hydra/ {next}
/spravok/ {next}
/spravka/ {next}
/zenit/ {next}
/zakladki/ {next}
/vullcan/ {next}
/vulslots/ {next}
/vulwinners/ {next}
/slots/ {next}
/traffaccess/ {next}
/tide24/ {next}
/swleon/ {next}
/sportingbull/ {next}
/sokol-24/ {next}
/silmag/ {next}
/faraon/ {next}
/marbet/ {next}
/joycazino/ {next}
/joy-cazino/ {next}
/jackpot/ {next}
/semyanich/ {next}
/semenarnia/ {next}
/prostitutki/ {next}
/shishkin-semena/ {next}
/vulkanstavka/ {next}
/bukvaved/ {next}
/rastarasha/ {next}
/errors-seeds/ {next}
/casino-x/ {next}
/kinogb/ {next}
/vulkanstars/ {next}
/vulcanwin/ {next}
/vlk-slots/ {next}
/rutorg/ {next}
/leonbets/ {next}
/parimatch/ {next}
/azartplay/ {next}
/bbplay2017/ {next}
/baltplay2017/ {next}
/hiwager/ {next}
/seedbanda/ {next}
#/gidonline/ {next}
/^alco/ {next}
(/\*/) {next}
(/\\/) {next} 
/svetacdn\.in/ {next}
/^a[bdfk]-[0-9]{5}/ {next}
/^azimob[0-9]{5}/ {next}
/^bets-.{2}-.{5}\./ {next}
/^betwinner-/ {next}
/^gg[0-9]{2,3}\.bet/ {next}
/^goldfishka[0-9]{2,3}\./ {next}
/^kinovod[0-9]{2,3}\.cc/ {next}
/^lite-1x/ {next}
/^livetv[0-9]{2,3}.me/ {next}
/^loot[0-9]{2,3}\.bet/ {next}
/^melbet-/ {next}
/^ox-[0-9]{5}/ {next}
/^partypoker[0-9]{3,5}\.com/ {next}
/^pin-up[0-9]{2,3}\./ {next}
/^pinup[0-9]{2,3}\./ {next}
/^pinupbet[0-9]{2,3}\./ {next}
/^pinupbk[0-9]{2,3}\./ {next}
/^zfilm-hd-[0-9]{3,4}\./ {next}
/appspot\.online/ {next}
/alko.*[0-9]{2,3}\./ {next}
/alco.*[0-9]{2,3}\./ {next}
/x-1xbet-/ {next}
/wylkan/ {next}
/wull[kc]an/ {next}
/wlnstar/ {next}
/wlnsport/ {next}
/winmaster/ {next}
/winbets/ {next}
/winbetline/ {next}
/vigronn/ {next}
/viagravnn/ {next}
/vegas-grand/ {next}
/^vavada/ {next}

/te[hx]osmotr/ {next}
/udostoverenie/ {next}
/tabak/ {next}
/swissking/ {next}
/sverhestestvennoe/ {next}
/^super/ {next}
/^study-/ {next}
/^stream/ {next}
/strahov/ {next}
/st-official/ {next}
/stavk[ia]/ {next}
/sprav/ {next}
/^sslkn/ {next}
/spt-trejd-/ {next}
/sporligtv/ {next}
/^spirt-/ {next}
/^sol-/ {next}
/^solaris/ {next}
/^sofosbuvir-/ {next}
/^slottica/ {next}
/^slotozal-/ {next}
/^semenacanabis/ {next}
/^selektor/ {next}
/^selector/ {next}
/^seedbaza/ {next}
/^ru-steroid/ {next}
/^refpa/ {next}
/^putlocker/ {next}
/^prava-/ {next}
/^onex/ {next}
/^omgomgomg5/ {next}
/^official-/ {next}
/^livetv[0-9]*\./ {next}
/^lite-betwin/ {next}
/^leon-official/ {next}
/^leon-registration/ {next}
/^kupit/ {next}
/^kinovod[0-9]*\./ {next}
/^eldo/ {next}
/^bkin-/ {next}
/^bitstar/ {next}
/^betwinner/ {next}
/^bet1-x/ {next}
/^bestpharma/ {next}
/^balashiha-grand/ {next}
/^apl[0-9]*\./ {next}
/dot-xenon-antonym/ {next}
/^zfilm-/ {next}
/^1win-/ {next}
/1-{0,1}xredir/ {next}
/1-{0,1}slot/ {next}
/1-{0,1}sport/ {next}
/apteka/ {next}
/do[ck]tor/ {next}
/^booi/ {next}
/^brill/ {next}
/goldfishka/ {next}
/^777/ {next}
/^888/ {next}
/^apl[0-9]/ {next}
/^aviator/ {next}
/^azimut/ {next}
/^azino/ {next}
/^bestseeds-/ {next}
/^betwinnwer-/ {next}
/^betwin-/ {next}
/^bitstarz/ {next}
/^blacksprut/ {next}
/^bongacams[0-9]/ {next}
/^bublik/ {next}
/^cabura/ {next}
/^champion-/ {next}
/^fort-prav/ {next}
/^fortprav/ {next}
/^g-trade/ {next}
/^indi[0-9]/ {next}
/^intimp[0-9]/ {next}
/^izzi-/ {next}
/zfilm-hd/ {next}
/zfilm[0-9]/ {next}
/zhahach/ {next}
/zeralo-v-a-v-a-d-a/ {next}
/vavada/ {next}
/wawada/ {next}
/zaliv-/ {next}
/zakon-kamennyh-dzhungley/ {next}
/zakis-/ {next}
/^zakis/ {next}
/^zagon/ {next}
/zarabot/ {next}
/^vzlom/ {next}
/^v[uy][l1][ck]/ {next}
/^vuzinfo/ {next}
/^up-x/ {next}
/^up[0-9]/ {next}
/^u[0-9][^0-9]/ {next}
/^trade/ {next}
/rastishki/ {next}
/rasta-/ {next}
/quantum/ {next}
/^prava/ {next}
/1xbet/ {next}
/1-xred/ {next}
/1xslo/ {next}
/^202[0123]/ {next}
/^apl/ {next}
/^apparat/ {next}
/^avalon/ {next}
/^azino/ {next}
/^azzino/ {next}
/^bank[^\.]/ {next}
/^bbrrigght/ {next}
/^beer/ {next}
/^belochka/ {next}
/^bet/ {next}
/^bonus/ {next}

# 25.07.2024
/^100/ {next}
/^1win/ {next}
/^1-win/ {next}
/^1xb/ {next}
/^1-xb/ {next}
/^7k-/ {next}
/^adm/ {next}
/^advokat/ {next}
/^agent/ {next}
/^aitfin/ {next}
/^ai-/ {next}
/^alepox/ {next}
/^alextra/ {next}
/^alletoper/ {next}
/^allserial/ {next}
/^allsteroid/ {next}
/^allxrtgof/ {next}
/^alrafiofs/ {next}
/^amarket/ {next}
/^anomiks/ {next}
/^answer/ {next}
/^apl.*\.me$/ {next}
/^aqua/ {next}
/^argo/ {next}
/^arteif/ {next}
/^ashoo/ {next}
/^astellia/ {next}
/^athletic/ {next}
/^binarium/ {next}
/^bitstar/ {next}
/^bkleon/ {next}
/^block4/ {next}
/^bo11y/ {next}
/^bollywood/ {next}
/^bomdogmas/ {next}
/^bomobd/ {next}
/^bs2/ {next}
/^crystal/ {next}
/^daclatasvir/ {next}
/^djplom/ {next}
/^drag/ {next}
/^drift/ {next}
/^fairspin/ {next}
/^go-game/ {next}
/^klub/ {next}
/^kraken/ {next}
/^livetv[0-9]*\.me$/ {next}
/^maxbet/ {next}
/^megamarket/ {next}
/^moskva-prava/ {next}
/^pinup/ {next}
/^pin-up/ {next}
/^ramen/ {next}
/^riobet/ {next}
/^salon/ {next}
/^sam-poehal/ {next}
/^schetchik/ {next}

/^zorgfilm/ {next}
/^zooma/ {next}
/^zetflix/ {next}
/^zercalo/ {next}
/^zakaz/ {next}
/^zagonka/ {next}
/^xdsakfsad/ {next}
/^wowofd/ {next}
/^win/ {next}
/^will/ {next}
/^vtrwo/ {next}
/^vse/ {next}
/^vremenn/ {next}
/^vovan/ {next}
/^voronezh/ {next}
/^voenkomat/ {next}
/^vodka/ {next}
/^v-lord/ {next}
/^sweet/ {next}
/^richclub/ {next}
/^registratsiya/ {next}
/^official/ {next}
/^mega5/ {next}

/^1lord/ {next}
/^1xlite/ {next}
/^24/ {next}
/^888/ {next}
/^ankustarmios/ {next}
/^apl/ {next}
/azino/ {next}
/^bio/ {next}
/^black/ {next}
/^bonga/ {next}
/^buff/ {next}
/^bvfusuv/ {next}
/^bvidks/ {next}
/^bwospa/ {next}
/^bxfilm/ {next}
/^caburo/ {next}

/^spin/ {next}
/^spir/ {next}
/^mebel/ {next}
/^medkn/ {next}
/^med-kn/ {next}
/^magn[ei]t/ {next}
/^magiksl/ {next}
/^m3ga/ {next}
/^luckyjet/ {next}
/^lucky-jet/ {next}
/^lordserial/ {next}
/^lordik/ {next}
/^lordfilm/ {next}

# Temporary
length($1) > 30 && !/wixmp/ {next}
/xn--/ {next}
#/^[0-9]/ {next}

# 14.10.2024
(/login/) {next}
(/signin/) {next}
(/bank/) {next}
(/secure/) {next}
(/verify/) {next}
(/account/) {next}
(/billing/) {next}
(/password/) {next}
(/invoice/) {next}
(/casino/) {next}
(/bet/) {next}
(/poker/) {next}
(/blackjack/) {next}
(/roulette/) {next}
(/slots/) {next}
(/winbig/) {next}
(/jackpot/) {next}
(/1win/) {next}
(/admiralx/) {next}
(/escort/) {next}
(/striptiz/) {next}
(/massaj/) {next}
(/stavki/) {next}
(/vulkan/) {next}
(/sloty/) {next}
(/prostitutki/) {next}
(/intim/) {next}
(/kokain/) {next}
(/xanax/) {next}
(/xanaks/) {next}
(/anasha/) {next}
(/escort/) {next}
(/pytana/) {next}
(/prostitutka/) {next}
(/metadon/) {next}
(/mefedron/) {next}
(/krokodil/) {next}
(/amfetamin/) {next}
(/drug/) {next}
(/narcotic/) {next}
(/meth/) {next}
(/weed/) {next}
(/vzyatka/) {next}
(/bribe/) {next}
(/russianbrides/) {next}
(/gamble/) {next}
(/blacksprut/) {next}

# 15.10.2024
(/ecstasy/) {next}
(/broker/) {next}
(/cas1no/) {next}
(/caseno/) {next}
(/casinno/) {next}
(/cosino/) {next}
#(/porno/) {next}
(/porn0/) {next}
(/xxx/) {next}
(/porevo/) {next}
(/bdsm/) {next}
(/gay/) {next}
(/pornp/) {next}
(/pussy/) {next}
(/pusy/) {next}
(/putana/) {next}
(/putanu/) {next}
(/putany/) {next}
(/qasino/) {next}
(/sex/) {next}
(/erotic/) {next}
(/cassa/) {next}
(/prava/) {next}
(/blowjob/) {next}
(/dosug/) {next}
(/amphetamin/) {next}
(/propiska/) {next}
(/malina/) {next}
(/bordel/) {next}
(/steroid/) {next}
(/slot/) {next}
(/e1dorado/) {next}
(/plati/) {next}
(/proctitytki/) {next}

#17.10.2024
(/orca88/) {next}
(/magnatov/) {next}
(/spin/) {next}
(/1xbet/) {next}
(/lucky/) {next}
(/1x-bet/) {next}
(/azin777/) {next}
(/absolut777/) {next}
(/psh-bk/) {next}
(/gig-games/) {next}
(/game24/) {next}
(/getx/) {next}

#21.10.2024
(/gamesgo/) {next}
(/^gamma/) {next}
(/ganja/) {next}
(/zaym/) {next}
(/stavochka/) {next}
(/stav0chka/) {next}
(/stavca/) {next}
(/stawca/) {next}
(/zadrot/) {next}
(/prostitytki/) {next}
(/prostitutku/) {next}
(/prostitutok/) {next}
(/prostitutky/) {next}

#24.10.2024
(/minet/) {next}
(/casoo/) {next}
(/casiino/) {next}
(/casin/) {next}
(/tabletka/) {next}
(/farma/) {next}
(/pasport/) {next}
(/payment/) {next}
(/korona/) {next}
(/devki/) {next}
(/devochki/) {next}
(/individualky/) {next}
(/girlss/) {next}
(/money/) {next}
(/feya/) {next}

# Обработка каждой строки
{
    print
}